In [18]:
import numpy as np
import pandas as pd

In [19]:
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer

In [20]:
df=pd.read_csv('covid_toy.csv')

In [21]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [22]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [23]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df.drop('has_covid',axis=1),df['has_covid'],test_size=0.2,random_state=42)
X_train

    age  gender  fever   cough       city
55   81  Female  101.0    Mild     Mumbai
88    5  Female  100.0    Mild    Kolkata
26   19  Female  100.0    Mild    Kolkata
42   27    Male  100.0    Mild      Delhi
69   73  Female  103.0    Mild      Delhi
..  ...     ...    ...     ...        ...
60   24  Female  102.0  Strong  Bangalore
71   75  Female  104.0  Strong      Delhi
14   51    Male  104.0    Mild  Bangalore
92   82  Female  102.0  Strong    Kolkata
51   11  Female  100.0  Strong    Kolkata

[80 rows x 5 columns]

**Tedious Way of Data Preprocessing(Without Column Transformer)**

In [24]:
imputer=SimpleImputer(strategy='median')
X_train_fever=imputer.fit_transform(X_train[['fever']])
X_test_fever=imputer.transform(X_test[['fever']])
X_train_fever

array([[101.],
       [100.],
       [100.],
       [100.],
       [103.],
       [103.],
       [102.],
       [101.],
       [101.],
       [101.],
       [ 98.],
       [104.],
       [103.],
       [104.],
       [100.],
       [101.],
       [104.],
       [102.],
       [102.],
       [103.],
       [104.],
       [102.],
       [101.],
       [104.],
       [102.],
       [101.],
       [ 99.],
       [101.],
       [104.],
       [102.],
       [100.],
       [ 98.],
       [ 98.],
       [101.],
       [100.],
       [100.],
       [101.],
       [104.],
       [101.],
       [103.],
       [101.],
       [ 98.],
       [ 99.],
       [ 99.],
       [101.],
       [ 99.],
       [101.],
       [104.],
       [ 98.],
       [101.],
       [103.],
       [101.],
       [ 98.],
       [ 99.],
       [ 98.],
       [ 99.],
       [102.],
       [101.],
       [101.],
       [104.],
       [100.],
       [ 98.],
       [100.],
       [101.],
       [100.],
       [100.],
       [ 98.],
       [101.],
       [ 98.],
       [101.],
       [101.],
       [104.],
       [104.],
       [ 98.],
       [ 98.],
       [102.],
       [104.],
       [104.],
       [102.],
       [100.]])

In [25]:
df['cough'].value_counts()

cough
Mild      62
Strong    38
Name: count, dtype: int64

In [26]:
oe=OrdinalEncoder(categories=[['Mild'  ,'Strong']])
X_train_cough=oe.fit_transform(X_train[['cough']])
X_test_cough=oe.transform(X_test[['cough']])
X_train_cough

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.]])

In [27]:
ohe=OneHotEncoder(sparse_output=False,drop='first')
X_train_gender_city=ohe.fit_transform(X_train[['gender','city']])
X_test_gender_city=ohe.transform(X_test[['gender','city']])
X_train

    age  gender  fever   cough       city
55   81  Female  101.0    Mild     Mumbai
88    5  Female  100.0    Mild    Kolkata
26   19  Female  100.0    Mild    Kolkata
42   27    Male  100.0    Mild      Delhi
69   73  Female  103.0    Mild      Delhi
..  ...     ...    ...     ...        ...
60   24  Female  102.0  Strong  Bangalore
71   75  Female  104.0  Strong      Delhi
14   51    Male  104.0    Mild  Bangalore
92   82  Female  102.0  Strong    Kolkata
51   11  Female  100.0  Strong    Kolkata

[80 rows x 5 columns]

In [28]:
X_train_age=X_train[['age']].values
X_test_age=X_test[['age']].values
X_train_age

array([[81],
       [ 5],
       [19],
       [27],
       [73],
       [70],
       [49],
       [51],
       [64],
       [83],
       [65],
       [18],
       [16],
       [16],
       [27],
       [84],
       [51],
       [69],
       [82],
       [69],
       [44],
       [74],
       [20],
       [12],
       [33],
       [42],
       [65],
       [23],
       [56],
       [64],
       [13],
       [31],
       [40],
       [49],
       [19],
       [11],
       [14],
       [42],
       [38],
       [46],
       [71],
       [10],
       [60],
       [22],
       [19],
       [65],
       [19],
       [54],
       [81],
       [20],
       [48],
       [82],
       [23],
       [66],
       [ 5],
       [49],
       [ 5],
       [34],
       [79],
       [ 6],
       [10],
       [69],
       [55],
       [34],
       [27],
       [47],
       [73],
       [42],
       [80],
       [47],
       [38],
       [34],
       [25],
       [24],
       [12],
       [24],
       [75],
       [51],
       [82],
       [11]], dtype=int64)

In [29]:
X_train_transformed = np.concatenate((X_train_age,X_train_fever,X_train_gender_city,X_train_cough),axis=1)
X_test_transformed = np.concatenate((X_test_age,X_test_fever,X_test_gender_city,X_test_cough),axis=1)
X_train_transformed.shape

(80, 7)

**Easy Process with the help of Column Transformer**

In [30]:
from sklearn.compose import ColumnTransformer

In [31]:
transformer=ColumnTransformer(transformers=[
    ('fever_imputer',SimpleImputer(strategy='median'),['fever']),
    ('cough_encoder',OrdinalEncoder(categories=[['Mild'  ,'Strong']]),['cough']),
    ('gender_city_encoder',OneHotEncoder(sparse_output=False,drop='first'),['gender','city'])
],remainder='passthrough')

In [32]:
transformer.fit_transform(X_train).shape

(80, 7)

In [33]:
transformer.transform(X_test).shape

(20, 7)